=== Dodri/C-Semesterarbeit/C-Semesterarbeit/Musiker.dtd
<!ELEMENT Plattenliste (Platte+)>
<!ELEMENT Platte (Albumtitel, Kuenstler, Entstehungsjahr, Ort, Plattenladen)>
<!ATTLIST Platte xml:id CDATA #REQUIRED>
<!ELEMENT Albumtitel (#PCDATA)>
<!ELEMENT Kuenstler (#PCDATA)>
<!ELEMENT Entstehungsjahr (#PCDATA)>
<!ELEMENT Ort (#PCDATA)>
<!ELEMENT Plattenladen (#PCDATA)>

=== Dodri/C-Semesterarbeit/C-Semesterarbeit/Musiker.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Plattenliste SYSTEM "Musiker.dtd">

<Plattenliste>

<Platte xml:id="1">
    <Albumtitel> 22, A Million </Albumtitel>
    <Kuenstler> Bon Iver </Kuenstler>
    <Entstehungsjahr> 2016 </Entstehungsjahr>
    <Ort> Koeln </Ort>
    <Plattenladen> Early Bird Records </Plattenladen>
    <Review>After a few years spent working on things other than Bon Iver, time spent sorting out heavy personal issues, and a radical rethink of the style that launched Justin Vernon's project to the upper reaches of indie folk popularity, the always searching musician returned in 2016 with an album that redefined Bon Iver in dramatic fashion. 22, A Million is a complicated and intricate record that features chopped-up lyrics, altered vocals, sped-up samples, alternately shimmering and clipped keyboards, treated saxophones, and the occasional gently strummed guitar. Through most of the challenging album, Vernon and his collaborators create miniature structures of sound and space, letting his vocals drift and cascade through sparse and fractured constructs like a lost soul wandering through empty futuristic streets. It's a long way from intimate folk songs recorded in a remote Wisconsin cabin. In the music, one can hear the influence of Vernon's occasional collaborator Kanye West, especially on the mutated R&B tracks like "10 d E A T h b R E a s T ⚄ ⚄" and "33 'God'," where his vocals take on a rap-like cadence, but also in the sense of grandeur and bombast intermittently found there and elsewhere. In direct contrast are the songs that sound very inward and emotionally bleak and twisted, possibly reflecting some of Vernon's struggles along the way. The desperate "715 - CR∑∑KS," which features nothing but a choir of Auto-Tuned Vernons singing aching lyrics that sound like they're being ripped from the deepest, darkest corner of his tortured soul, is maybe the darkest track. In yet more contrast, a few songs on the album retain much of the hushed acoustic feel of his earlier albums, but with weird electronics and tricks around the edges. The beautiful "29 #Strafford APTS" is a folk song at its core, but he adds altered vocals, queasily pitched saxophones, and distorted electronic tones to provide some drama to the song. He does similar things to the album-ending piano ballad "00000 Million" and the tense, almost ambient "21 M◊◊N WATER," turning them from typically sad Bon Iver songs into something weird and oddly more affecting. The only track on the album that falls short of the standard set elsewhere is "8 (circle)," which makes the mistake of being a little too earnestly straightforward and too much like a Bruce Hornsby song. This was probably the one that needed the most manipulation, and it's the one that gets the least. One little misstep can't keep 22, A Million from being a return to form, even as it turns the established form on its head and gives it a spin. It's clear that the upheavals in Vernon's life and music are a matched set; he turns his pain into art as he does a deep dive into exploration of technique and sound. It's an impressive feat of reinvention that manages to keep Vernon's emotional core fully intact no matter how far the music strays from established Bon Iver territory. </Review>
</Platte>

<Platte xml:id="2">
    <Albumtitel> Palmen und Beats </Albumtitel>
    <Kuenstler> Dexter </Kuenstler>
    <Entstehungsjahr> 2015 </Entstehungsjahr>
    <Ort> Hamburg </Ort>
    <Plattenladen> Slam Records </Plattenladen>
    <Review> Palmen und Beats ist Dexters Instrumentalversion von seinem Klassiker 'Palmen & Freunde'.Es klingt ziemlich genau so, wie wenn du mit deinen Kumpels in deinem Dorf oder deiner Kleinstadt oder deiner Großstadt in einem kühlen Kellerraum abhängst, staubige Platten auflegst und neben der Sportzigarette auch das Mic kreist. Mit dem kleinen, aber feinen Unterschied, dass hier Dexters 1a-Qualitäts-Beats die Grundlagen bieten und am Mic neben dem Produzenten selbst Meister ihres Fachs wie Morlockk Dilemma, Döll, Audio88, Yassin, Fatoni, Mädness, Sonne Ra oder Chefket aktiv sind.Und, nix gegen dich oder deine Kumpels, aber die machen das halt alle schon bisschen was länger und dementsprechend auch besser. - rap.de </Review>
</Platte>

<Platte xml:id="3">
    <Albumtitel> I Put A Spell On You </Albumtitel>
    <Kuenstler> Nina Simone </Kuenstler>
    <Entstehungsjahr> 1965 </Entstehungsjahr>
    <Ort> Berlin </Ort>
    <Plattenladen> Soultrade Recordstore </Plattenladen>
    <Review> One of her most pop-oriented albums, but also one of her best and most consisten. Most of the songs feature dramatic, swining large-band orchestration, with the accent on the brass and strings. Simone didn't write any of the material, turning to popular European songsmiths Charles Aznavour, Jacques Brel, and Anthony Newley, as well as her husband, Andy Stroud, and her guitarist, Rudy Stevenson, for bluesier fare. There are really fine tunes and interpretations, on which Simone gives an edge to the potentially fey pop songs, taking a sudden break for a straight jazz instrumental with 'Blues on Purpose'. The title track, a jazzy string ballad version of the Screamin' Jay Hawkins classic, gave the Veatles the inspiration for the phrasing on the bridge of 'Michelle'. - allmusic.com </Review>
</Platte>

<Platte xml:id="4">
    <Albumtitel> Winelight </Albumtitel>
    <Kuenstler> Groove Washington Jr </Kuenstler>
    <Entstehungsjahr> 1980 </Entstehungsjahr>
    <Ort> Koeln </Ort>
    <Plattenladen> Underground Recordstore </Plattenladen>
    <Review> Grover Washington, Jr., has long been one of the leaders in what could be called rhythm& jazz, essentially R&B-influenced jazz. Winelight is one of his finest albums, and not primarily because of the Bill Withers hit "Just the Two of Us." It is the five instrumentals that find Washington (on soprano, alto, and teno) really stretching out. If he had been only interested in sales, Washington's solos could have been half as long and he would have stuck closely to the melodie. Instead he really pushes himself on some of these selections, particularly the title cut. A memorable set of high-quality and danceable soul-jazz. - allmusic.com</Review>
</Platte>

<Platte xml:id="5">
    <Albumtitel> The Arc Of Tension </Albumtitel>
    <Kuenstler> Oliver Koletzki </Kuenstler>
    <Entstehungsjahr> 2017 </Entstehungsjahr>
    <Ort> Berlin </Ort>
    <Plattenladen> Melting Point Recordstore </Plattenladen>
    <Review> On his sixth album, The Arc Of Tension, the Berlin based DJ, label owner, and producer Oliver Koletzki yet again presents his remarkable vision of contemporary electronic music, while also assuming the role of a storyteller. The Arc Of Tension speaks to its listener as a singular, self-contained work, which communicates by way of its natural flow and arc of suspense. The latter is mirrored not only in the multifarious narrative of the actual album, but can also be understood as evidence for its creator's long musical history. While Koletzki focused on a diverse range of vocal collaborations on his previous long players, he now moves on to a different form of storytelling, rooted in the quiet confidence of a veteran musician, as well as the hectic lifestyle of a globally in demand DJ. The Arc Of Tension is a psychonautic journey through the various continents of Oliver's consciousness. The quiet chirps and warbles, which initially unfold on the opener "A Tribe Called Kotori", thus act as a loose associative bridge to Der Mückenschwarm, Oliver's big breakthrough hit of 2005. The first minutes of the album leave no room for doubt -- the listener is immediately locked into and captivated by an autobiographical world of sound. The dreamy, exotic timbres of the downbeat tracks "By My Side", "Tankwa Town", and "Byron Bay" are penetrating, but in a subtle yet purposeful manner. But soon the tension tightens and organic sounds, one-by-one, evolve towards a sterner, electronic cadence. The bittersweet neon synths of "Spiritual But Not Religious" pave the way for the complex rhythm of "A Star Called Akasha", an early highlight carried by melancholic cellos and contemplative piano chords. The ultimate turning point follows with "Through The Darkness". Here, at the album's center, Koletzki starts continuously upping the tempo and leads the way with his very own, melodic interpretation of today's techno Zeitgeist, exemplifying that a fusion of delicate musicality and sheer force leads to impressively ecstatic results. You fully take off into space, weightlessly propelled by the ambient drones of "The Day We Leave Earth". Ultimately, what lingers is the feeling that The Arc Of Tension is a deep glance into the innermost being of an outstanding artist. -forcedexposure.com </Review>
</Platte>

<Platte xml:id="6">
    <Albumtitel> Stakes Is High </Albumtitel>
    <Kuenstler> De La Soul </Kuenstler>
    <Entstehungsjahr> 1986 </Entstehungsjahr>
    <Ort> Amsterdam </Ort>
    <Plattenladen> Red Light Records </Plattenladen>
